language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
install:
  # Composer
  - composer self-update
  - composer install -n --prefer-source
  # Database
  - mysql -e 'CREATE DATABASE testdb;'
before_script:
  # Directories
  - mkdir .reports
  # Config file
  - cp tests/src/config.dist.php tests/src/config.php
script:
  # Tests
  - php vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover=.reports/clover.xml --coverage-xml=.reports/coverage
  # Code style
  - php vendor/bin/phpcs --report=xml --report-file=.reports/phpcs.xml
after_script:
  # Coveralls
  - php vendor/bin/coveralls -v